"""Remote-code bundle writer for self-contained exported model directories."""

from __future__ import annotations

import os
import re
from ml.integrations.export.runtime_packager_manifest import (
    EXPORT_MODELING_FILENAME,
    EXPORT_MODELING_MODULE,
    EXPORT_RUNTIME_BACKEND_FILENAME,
    REMOTE_CODE_BUNDLE_MANIFEST,
    RemoteCodeArtifact,
)

_EXPORT_BANNER = (
    "# Generated by ml.integrations.export.runtime_packager.write_remote_code_bundle.\n"
    "# Exported for HuggingFace trust_remote_code loading.\n"
    "# This file is intentionally self-contained.\n\n"
)


def _resolve_package_root(repo_root: str | None = None) -> str:
    root = str(repo_root or "").strip()
    if not root:
        root = os.path.abspath(os.path.join(os.path.dirname(__file__), "../../.."))
    candidate = os.path.join(str(root), "ml")
    if os.path.isdir(candidate):
        return str(root)
    return os.path.abspath(str(root))


def _source_module_name(artifact: RemoteCodeArtifact) -> str:
    relpath = artifact.source_relpath
    stem, _ = os.path.splitext(relpath[-1])
    if stem == "__init__":
        return ".".join(relpath[:-1])
    return ".".join((*relpath[:-1], stem))


def _export_module_name(artifact: RemoteCodeArtifact) -> str:
    stem, _ = os.path.splitext(artifact.output_filename)
    return stem


def _rewrite_export_imports(source: str) -> str:
    module_map = {
        _source_module_name(artifact): _export_module_name(artifact)
        for artifact in REMOTE_CODE_BUNDLE_MANIFEST
    }
    module_map["ml.integrations.adapters.hf.model"] = EXPORT_MODELING_MODULE
    rewritten = source
    for source_module, export_module in module_map.items():
        rewritten = re.sub(
            rf"(?m)^(\s*from\s+){re.escape(source_module)}(\s+import\s+)",
            rf"\1.{export_module}\2",
            rewritten,
        )
        rewritten = re.sub(
            rf"(?m)^(\s*import\s+){re.escape(source_module)}(\s+as\s+)",
            rf"from . import {export_module}\2",
            rewritten,
        )
        rewritten = rewritten.replace(f'"{source_module}"', f'"{export_module}"')
        rewritten = rewritten.replace(f"'{source_module}'", f"'{export_module}'")
    return rewritten


def _inject_export_primers(
    *,
    artifact: RemoteCodeArtifact,
    source: str,
) -> str:
    if artifact.output_filename != EXPORT_MODELING_FILENAME:
        return source
    marker = "from __future__ import annotations\n\n"
    dependency_modules = []
    seen_modules: set[str] = set()
    for dep in REMOTE_CODE_BUNDLE_MANIFEST:
        if dep.output_filename == EXPORT_MODELING_FILENAME:
            continue
        module_name = _export_module_name(dep)
        if module_name in seen_modules:
            continue
        seen_modules.add(module_name)
        dependency_modules.append(module_name)
    dependency_imports = "\n".join(
        f"    from .{module_name} import *  # noqa: F401,F403"
        for module_name in dependency_modules
    )
    primer = (
        "from typing import TYPE_CHECKING\n\n"
        "from .sophia_runtime import Transformer as _SophiaRuntimeTransformer  # noqa: F401\n\n"
        "if TYPE_CHECKING:\n"
        f"{dependency_imports}\n\n"
    )
    if primer in source or marker not in source:
        return source
    return source.replace(marker, f"{marker}{primer}", 1)


def _rewrite_runtime_backend_module_name(
    *,
    artifact: RemoteCodeArtifact,
    source: str,
) -> str:
    if artifact.output_filename != EXPORT_RUNTIME_BACKEND_FILENAME:
        return source
    return source.replace(
        '"sophia_runtime"',
        '".sophia_runtime"',
    )


def _render_exported_artifact(*, source_path: str, artifact: RemoteCodeArtifact) -> str:
    with open(str(source_path), encoding="utf-8") as handle:
        source = _rewrite_export_imports(handle.read())
    source = _inject_export_primers(artifact=artifact, source=source)
    source = _rewrite_runtime_backend_module_name(artifact=artifact, source=source)
    if source.startswith(_EXPORT_BANNER):
        return source
    return f"{_EXPORT_BANNER}{source}"


def _write_exported_artifact(*, output_path: str, content: str) -> None:
    with open(str(output_path), "w", encoding="utf-8", newline="\n") as handle:
        handle.write(content)


def write_remote_code_bundle(*, output_dir: str, repo_root: str | None = None) -> None:
    os.makedirs(str(output_dir), exist_ok=True)
    pkg_root = _resolve_package_root(repo_root)
    for artifact in REMOTE_CODE_BUNDLE_MANIFEST:
        _write_exported_artifact(
            output_path=os.path.join(str(output_dir), artifact.output_filename),
            content=_render_exported_artifact(
                source_path=os.path.join(str(pkg_root), *artifact.source_relpath),
                artifact=artifact,
            ),
        )


__all__ = [
    "REMOTE_CODE_BUNDLE_MANIFEST",
    "RemoteCodeArtifact",
    "write_remote_code_bundle",
]
