from __future__ import annotations

PRETRAIN_LOG_TAG = "MACHINE"
PRETRAIN_MACHINE_RECIPE_SUMMARY = "machine_recipe_summary.json"
PRETRAIN_MACHINE_RECIPE_ARTIFACT = "machine_recipe.json"
PRETRAIN_MACHINE_RUNTIME_ARTIFACT = "machine_runtime.json"
PRETRAIN_UPDATE_PROFILE_ARTIFACT = "update_profile.json"
PRETRAIN_PROFILE_ARTIFACT = "pretrain_profile.json"
PRETRAIN_SIGNED_MACHINE_RECIPE_ARTIFACT = "release_pretrain_machine_recipe.json"


__all__ = [
    "PRETRAIN_LOG_TAG",
    "PRETRAIN_MACHINE_RECIPE_ARTIFACT",
    "PRETRAIN_MACHINE_RECIPE_SUMMARY",
    "PRETRAIN_MACHINE_RUNTIME_ARTIFACT",
    "PRETRAIN_PROFILE_ARTIFACT",
    "PRETRAIN_SIGNED_MACHINE_RECIPE_ARTIFACT",
    "PRETRAIN_UPDATE_PROFILE_ARTIFACT",
]
