from __future__ import annotations

import os

DEFAULT_POSTTRAIN_CURRICULUM_PATH = os.path.join(
    "dataset",
    "posttrain_length_curriculum.json",
)

# Release post-train semantic defaults shared by local and training machines.
RELEASE_SFT_CURRICULUM_STAGE = "sft_core"
RELEASE_SFT_TARGET_EXAMPLES_PER_UPDATE = 16
RELEASE_SFT_LEARNING_RATE = 5e-6
RELEASE_SFT_WEIGHT_DECAY = 0.1
RELEASE_SFT_MAX_STEPS = 1000
RELEASE_SFT_EVAL_INTERVAL = 100
RELEASE_SFT_EVAL_STEPS = 16
RELEASE_SFT_SAVE_INTERVAL = 100
RELEASE_SFT_REPORT_MAX_EXAMPLES_PER_SPLIT = 0
RELEASE_SFT_REPORT_PROGRESS_EVERY = 25

# Lightweight same-chain machine-selection defaults.
MACHINE_SELECTION_SFT_MAX_STEPS = 8
MACHINE_SELECTION_SFT_EVAL_STEPS = 8
MACHINE_SELECTION_SFT_REPORT_MAX_EXAMPLES_PER_SPLIT = 8
MACHINE_SELECTION_SFT_REPORT_PROGRESS_EVERY = 4

# Full-chain rehearsal defaults. These are explicitly downscaled for fast local validation.
REHEARSAL_SFT_MAX_STEPS = 2
REHEARSAL_POSTTRAIN_BATCH_SIZE = 1
REHEARSAL_POSTTRAIN_EVAL_STEPS = 1
REHEARSAL_POSTTRAIN_REPORT_MAX_EXAMPLES_PER_SPLIT = 0
REHEARSAL_POSTTRAIN_REPORT_PROGRESS_EVERY = 25
