from __future__ import annotations

import argparse
from collections import Counter, defaultdict, deque
from collections.abc import Iterable, Iterator
from concurrent.futures import Future, ProcessPoolExecutor
import gzip
import hashlib
from itertools import batched
import json
import multiprocessing
import os
from pathlib import Path
import re
import shutil
import sqlite3
import struct
from typing import Any

import pyarrow as pa
import pyarrow.parquet as pq

from ml.core.common.io import write_json_atomic
from ml.data.pretrain_filters import is_poison_repetitive_text, normalize_text
from ml.tooling.scripts.data.corpus_quality import (
    BenchmarkMatcher,
    CleanDecision,
    clean_document,
    dedup_normalize,
    document_split,
    near_duplicate_signature,
    near_signature_similarity,
)
from ml.tooling.scripts.data.download_hf_source_inventory import sha256_file
from ml.tooling.scripts.data.train_chinese_quality_proxy import (
    MODEL_SCHEMA as QUALITY_PROXY_MODEL_SCHEMA,
    REPORT_SCHEMA as QUALITY_PROXY_REPORT_SCHEMA,
    load_quality_proxy,
    score_quality_texts,
)


REPORT_SCHEMA = "sophia_clean_pretrain_corpus_v1"
LEGACY_EXCLUSION_SCHEMA = "sophia_legacy_content_exclusion_v1"
LEGACY_INDEX_SCHEMA = "sha256_nfkc_casefold_remove_whitespace_v1"
LEGACY_DEPRECATED_NEAR_INDEX_SCHEMA = (
    "sha256_nfkc_casefold_remove_whitespace_plus_bottom8_char5_v2"
)
LEGACY_NEAR_INDEX_SCHEMA = "sha256_nfkc_casefold_remove_whitespace_plus_cdc_minhash8_v3"
_CJK_RE = re.compile(r"[\u3400-\u4dbf\u4e00-\u9fff]")
_LATIN_RE = re.compile(r"[A-Za-z]")
_TIMESTAMP_YEAR_RE = re.compile(r"^(19[0-9]{2}|20[0-9]{2}|2100)(?:[-T]|$)")
_CODE_VENDOR_PATH_RE = re.compile(
    r"(?:^|/)(?:node_modules|bower_components|vendor|third[_-]?party|"
    r"site-packages|dist|build)(?:/|$)",
    re.IGNORECASE,
)
_CODE_GENERATED_RE = re.compile(
    r"\b(?:auto[- ]?generated|generated by|do not edit|machine generated)\b",
    re.IGNORECASE,
)
_CODE_PROPRIETARY_RE = re.compile(
    r"\b(?:unpublished proprietary|commercial license|confidential information|"
    r"unauthorized copying)\b",
    re.IGNORECASE,
)
_CODE_SECRET_RES = (
    re.compile(r"-----BEGIN (?:RSA |EC |OPENSSH )?PRIVATE KEY-----"),
    re.compile(r"\b(?:AKIA|ASIA)[A-Z0-9]{16}\b"),
    re.compile(
        r"\beyJ[A-Za-z0-9_-]{10,}\.[A-Za-z0-9_-]{10,}\."
        r"[A-Za-z0-9_-]{10,}\b"
    ),
)
_CODE_BASE64_BLOB_RE = re.compile(r"[A-Za-z0-9+/]{1000,}={0,2}")


def _load_json(path: str | Path) -> dict[str, Any]:
    with open(path, encoding="utf-8") as handle:
        payload = json.load(handle)
    if not isinstance(payload, dict):
        raise ValueError(f"expected JSON object: {path}")
    return payload


def _json_sha256(path: str | Path) -> str:
    return hashlib.sha256(Path(path).resolve().read_bytes()).hexdigest()


def _acquisition_content_sha256(acquisition: dict[str, Any]) -> str:
    """Digest the corpus an acquisition bundle designates, not its serialization.

    The bundle is re-materialized on every pipeline start and embeds derivative
    report hashes, so its raw bytes differ between runs that select exactly the
    same files. Resume must key off the selected corpus itself: source identity
    plus the sorted per-file content hashes. A genuinely different corpus still
    changes this digest and still trips the resume gate.
    """

    identity = [
        [
            str(source.get("name") or ""),
            str(source.get("repo_id") or ""),
            str(source.get("revision") or ""),
            sorted(
                [str(row.get("path") or ""), str(row.get("sha256") or "")]
                for row in source.get("files", [])
            ),
        ]
        for source in acquisition.get("sources", [])
    ]
    identity.sort()
    canonical = json.dumps(identity, ensure_ascii=False, separators=(",", ":"))
    return hashlib.sha256(canonical.encode("utf-8")).hexdigest()


def _is_relative_to(path: Path, root: Path) -> bool:
    try:
        path.relative_to(root)
    except ValueError:
        return False
    return True


def _validate_admission_policy(
    *,
    acquisition: dict[str, Any],
    policy_path: str,
) -> tuple[dict[str, Any], str]:
    policy_file = Path(policy_path).expanduser().resolve()
    policy = _load_json(policy_file)
    if str(policy.get("schema")) != "sophia_pretrain_data_admission_policy_v1":
        raise ValueError("unsupported pretrain data admission policy")
    if bool(policy.get("allow_legacy_assets_as_training_input")):
        raise ValueError("admission policy must forbid legacy training inputs")
    raw_root = Path(str(acquisition.get("output_root") or "")).expanduser().resolve()
    repo_root = Path(__file__).resolve().parents[4]
    for value in policy.get("forbidden_input_roots", []):
        forbidden = Path(str(value)).expanduser()
        if not forbidden.is_absolute():
            forbidden = repo_root / forbidden
        forbidden = forbidden.resolve()
        if raw_root == forbidden or _is_relative_to(raw_root, forbidden):
            raise ValueError(f"legacy training input is forbidden: {raw_root}")
    return policy, _json_sha256(policy_file)


def _validate_inventory_upstreams(
    *,
    inventory: dict[str, Any],
    policy: dict[str, Any],
) -> None:
    forbidden = {
        str(value).strip().casefold()
        for value in policy.get("forbidden_upstream_repo_ids", [])
        if str(value).strip()
    }
    for source in inventory.get("sources", []):
        if not isinstance(source, dict):
            raise ValueError("inventory source rows must be objects")
        repo_id = str(source.get("repo_id") or "").strip()
        if not repo_id:
            raise ValueError("inventory source has no repo_id")
        if repo_id.casefold() in forbidden:
            raise ValueError(f"legacy upstream repository is forbidden: {repo_id}")


def _validate_benchmark_decontamination(
    *,
    policy: dict[str, Any],
    benchmark_paths: list[str],
) -> list[str]:
    repo_root = Path(__file__).resolve().parents[4]
    provided: dict[Path, str] = {}
    for value in benchmark_paths:
        path = Path(str(value)).expanduser()
        if not path.is_absolute():
            path = (Path.cwd() / path).resolve()
        else:
            path = path.resolve()
        if path in provided:
            raise ValueError(f"duplicate benchmark decontamination asset: {path}")
        if not path.is_file():
            raise FileNotFoundError(f"missing benchmark decontamination asset: {path}")
        provided[path] = str(path)

    config = policy.get("benchmark_decontamination")
    if not isinstance(config, dict) or not bool(config.get("required")):
        return list(provided.values())
    required = config.get("required_signature_assets")
    if not isinstance(required, list) or not required:
        raise ValueError(
            "required benchmark decontamination has no pinned signature assets"
        )
    for asset in required:
        if not isinstance(asset, dict):
            raise ValueError("benchmark decontamination assets must be objects")
        required_path = Path(str(asset.get("path") or "")).expanduser()
        if not required_path.is_absolute():
            required_path = repo_root / required_path
        required_path = required_path.resolve()
        if required_path not in provided:
            raise ValueError(
                f"missing required benchmark decontamination asset: {required_path}"
            )
        expected_sha256 = str(asset.get("sha256") or "").lower()
        actual_sha256 = sha256_file(required_path).lower()
        if len(expected_sha256) != 64 or actual_sha256 != expected_sha256:
            raise ValueError(
                "benchmark decontamination asset sha256 mismatch: "
                f"{required_path} expected={expected_sha256} actual={actual_sha256}"
            )
        expected_rows = int(asset.get("signatures") or 0)
        if expected_rows <= 0:
            raise ValueError(
                f"benchmark decontamination signature count is invalid: {required_path}"
            )
        with required_path.open(encoding="utf-8") as handle:
            actual_rows = sum(1 for line in handle if line.strip())
        if actual_rows != expected_rows:
            raise ValueError(
                "benchmark decontamination signature count mismatch: "
                f"{required_path} expected={expected_rows} actual={actual_rows}"
            )
    return list(provided.values())


def _validate_acquisition(
    *,
    acquisition_path: str,
    policy_path: str,
) -> tuple[dict[str, Any], dict[str, Any], dict[str, Any], str, str]:
    acquisition_file = Path(acquisition_path).expanduser().resolve()
    acquisition = _load_json(acquisition_file)
    if str(acquisition.get("schema")) != "sophia_hf_acquisition_report_v1":
        raise ValueError("unsupported acquisition report")
    policy, policy_sha256 = _validate_admission_policy(
        acquisition=acquisition,
        policy_path=policy_path,
    )
    inventory_path = Path(str(acquisition.get("inventory_path") or "")).resolve()
    inventory = _load_json(inventory_path)
    if str(inventory.get("schema")) != "sophia_hf_source_inventory_v2":
        raise ValueError("production cleaning requires a v2 source inventory")
    _validate_inventory_upstreams(inventory=inventory, policy=policy)
    inventory_sha256 = _json_sha256(inventory_path)
    recorded_inventory_sha256 = str(acquisition.get("inventory_sha256") or "")
    if recorded_inventory_sha256 != inventory_sha256:
        raise ValueError(
            "acquisition inventory sha256 mismatch: "
            f"recorded={recorded_inventory_sha256} actual={inventory_sha256}"
        )
    acquired_sources = {
        str(source.get("name") or ""): source
        for source in acquisition.get("sources", [])
        if isinstance(source, dict)
    }
    inventory_sources = {
        str(source.get("name") or ""): source
        for source in inventory.get("sources", [])
        if isinstance(source, dict)
    }
    if set(acquired_sources) != set(inventory_sources):
        raise ValueError(
            "acquisition sources do not exactly match the pinned inventory"
        )
    for name, source in inventory_sources.items():
        expected = {
            str(item.get("path") or ""): item
            for item in source.get("files", [])
            if isinstance(item, dict)
        }
        actual = {
            str(item.get("filename") or ""): item
            for item in acquired_sources[name].get("files", [])
            if isinstance(item, dict)
        }
        if set(actual) != set(expected):
            raise ValueError(f"acquired file list does not match inventory: {name}")
        for filename, expected_row in expected.items():
            actual_row = actual[filename]
            if int(actual_row.get("bytes") or 0) != int(expected_row.get("bytes") or 0):
                raise ValueError(f"acquired file size drift: {name}/{filename}")
            if str(actual_row.get("sha256") or "") != str(
                expected_row.get("sha256") or ""
            ):
                raise ValueError(f"acquired file sha256 drift: {name}/{filename}")
    return acquisition, inventory, policy, policy_sha256, inventory_sha256


def _ordered_acquisition_sources(acquisition: dict[str, Any]) -> list[dict[str, Any]]:
    indexed: list[tuple[int, int, dict[str, Any]]] = []
    for index, source in enumerate(acquisition.get("sources", [])):
        if not isinstance(source, dict):
            continue
        raw_priority = source.get("deduplication_priority", 0)
        if isinstance(raw_priority, bool) or not isinstance(raw_priority, int):
            raise ValueError("source deduplication_priority must be an integer")
        priority = int(raw_priority)
        if not 0 <= priority <= 1_000:
            raise ValueError("source deduplication_priority must be in [0, 1000]")
        indexed.append((priority, index, source))
    return [
        source
        for _priority, _index, source in sorted(
            indexed,
            key=lambda item: (-item[0], item[1]),
        )
    ]


def _resolve_policy_path(value: object) -> Path:
    path = Path(str(value or "")).expanduser()
    if not path.is_absolute():
        path = Path(__file__).resolve().parents[4] / path
    return path.resolve()


def _paths_refer_to_same_object(left: Path, right: Path) -> bool:
    try:
        return left.samefile(right)
    except OSError:
        return False


def _same_filesystem_objects(expected: set[Path], actual: set[Path]) -> bool:
    if len(expected) != len(actual):
        return False
    unmatched = list(actual)
    for expected_path in expected:
        match_index = next(
            (
                index
                for index, actual_path in enumerate(unmatched)
                if expected_path == actual_path
                or _paths_refer_to_same_object(expected_path, actual_path)
            ),
            None,
        )
        if match_index is None:
            return False
        unmatched.pop(match_index)
    return not unmatched


class LegacyContentExclusion:
    def __init__(
        self,
        *,
        report_path: Path | None = None,
        database_path: Path | None = None,
        report_sha256: str = "",
        database_sha256: str = "",
        index_schema: str = "",
        near_threshold: float = 0.75,
        action: str = "exclude",
    ) -> None:
        self.report_path = report_path
        self.database_path = database_path
        self.report_sha256 = str(report_sha256)
        self.database_sha256 = str(database_sha256)
        self.index_schema = str(index_schema)
        self.near_threshold = float(near_threshold)
        self.action = str(action)
        if self.action not in {"exclude", "report"}:
            raise ValueError("legacy content overlap action must be exclude or report")
        self.connection: sqlite3.Connection | None = None
        if database_path is not None:
            self.connection = sqlite3.connect(
                f"file:{database_path}?mode=ro",
                uri=True,
                timeout=120.0,
            )
            if self.index_schema == LEGACY_NEAR_INDEX_SCHEMA:
                tables = {
                    str(row[0])
                    for row in self.connection.execute(
                        "SELECT name FROM sqlite_master WHERE type = 'table'"
                    )
                }
                missing = sorted({"hashes", "signatures", "bands"} - tables)
                if missing:
                    self.connection.close()
                    self.connection = None
                    raise ValueError(
                        f"legacy near-content index is missing tables: {missing}"
                    )

    @property
    def enabled(self) -> bool:
        return self.connection is not None

    def contains(self, document_sha256: str) -> bool:
        if self.connection is None:
            return False
        try:
            digest = bytes.fromhex(str(document_sha256))
        except ValueError as exc:
            raise ValueError("invalid document sha256 for legacy exclusion") from exc
        return (
            self.connection.execute(
                "SELECT 1 FROM hashes WHERE sha256 = ?",
                (sqlite3.Binary(digest),),
            ).fetchone()
            is not None
        )

    def contains_near(self, signature: tuple[int, ...]) -> bool:
        if self.connection is None or self.index_schema != LEGACY_NEAR_INDEX_SCHEMA:
            return False
        bands = _near_lookup_band_keys(signature)
        if not bands:
            return False
        placeholders = ",".join("?" for _ in bands)
        rows = self.connection.execute(
            "SELECT DISTINCT s.signature FROM bands b "
            "JOIN signatures s ON s.sha256 = b.sha256 "
            f"WHERE b.band_key IN ({placeholders})",
            tuple(sqlite3.Binary(value) for value in bands),
        )
        for row in rows:
            candidate = _signature_from_blob(bytes(row[0]))
            similarity = near_signature_similarity(signature, candidate)
            if similarity >= self.near_threshold:
                return True
        return False

    def classify_batch(
        self,
        documents: list[tuple[str, tuple[int, ...]]],
    ) -> list[tuple[bool, bool]]:
        if self.connection is None or not documents:
            return [(False, False) for _document in documents]
        digests: list[bytes] = []
        for document_sha256, _signature in documents:
            try:
                digests.append(bytes.fromhex(str(document_sha256)))
            except ValueError as exc:
                raise ValueError(
                    "invalid document sha256 for legacy exclusion"
                ) from exc
        exact_digests: set[bytes] = set()
        for offset in range(0, len(digests), 500):
            chunk = digests[offset : offset + 500]
            placeholders = ",".join("?" for _ in chunk)
            exact_digests.update(
                bytes(row[0])
                for row in self.connection.execute(
                    f"SELECT sha256 FROM hashes WHERE sha256 IN ({placeholders})",
                    tuple(sqlite3.Binary(value) for value in chunk),
                )
            )
        exact_matches = [digest in exact_digests for digest in digests]
        if self.index_schema != LEGACY_NEAR_INDEX_SCHEMA:
            return [(exact, False) for exact in exact_matches]

        document_bands = [
            () if exact else _near_lookup_band_keys(signature)
            for exact, (_sha256, signature) in zip(
                exact_matches,
                documents,
                strict=True,
            )
        ]
        all_bands = sorted({band for bands in document_bands for band in bands})
        existing_by_band: dict[bytes, set[bytes]] = defaultdict(set)
        for offset in range(0, len(all_bands), 500):
            bands = all_bands[offset : offset + 500]
            placeholders = ",".join("?" for _ in bands)
            rows = self.connection.execute(
                "SELECT b.band_key, s.signature FROM bands b "
                "JOIN signatures s ON s.sha256 = b.sha256 "
                f"WHERE b.band_key IN ({placeholders})",
                tuple(sqlite3.Binary(value) for value in bands),
            )
            for band, signature_blob in rows:
                existing_by_band[bytes(band)].add(bytes(signature_blob))

        results: list[tuple[bool, bool]] = []
        for exact, (_sha256, signature), bands in zip(
            exact_matches,
            documents,
            document_bands,
            strict=True,
        ):
            if exact:
                results.append((True, False))
                continue
            candidate_blobs: set[bytes] = set()
            for band in bands:
                candidate_blobs.update(existing_by_band.get(band, ()))
            near = False
            for candidate_blob in candidate_blobs:
                candidate = _signature_from_blob(candidate_blob)
                similarity = near_signature_similarity(signature, candidate)
                if similarity >= self.near_threshold:
                    near = True
                    break
            results.append((False, near))
        return results

    def close(self) -> None:
        if self.connection is not None:
            self.connection.close()


def _load_legacy_content_exclusion(
    *,
    policy: dict[str, Any],
) -> LegacyContentExclusion:
    config = policy.get("legacy_content_exclusion")
    if not isinstance(config, dict):
        return LegacyContentExclusion()
    if not bool(config.get("required")):
        raise ValueError("configured legacy content exclusion must be required")
    match_mode = str(config.get("match_mode") or "")
    if match_mode not in {
        "exact_sha256_of_nfkc_casefold_remove_whitespace",
        "exact_sha256_plus_cdc_minhash8_near_overlap",
    }:
        raise ValueError("unsupported legacy content exclusion match mode")
    action = str(config.get("action") or "exclude")
    if action not in {"exclude", "report"}:
        raise ValueError("legacy content overlap action must be exclude or report")
    report_path = _resolve_policy_path(config.get("report_path"))
    expected_report_sha256 = str(config.get("report_sha256") or "").lower()
    expected_database_sha256 = str(config.get("database_sha256") or "").lower()
    if len(expected_report_sha256) != 64 or len(expected_database_sha256) != 64:
        raise ValueError(
            "legacy content exclusion requires pinned report and database sha256"
        )
    actual_report_sha256 = _json_sha256(report_path)
    if actual_report_sha256 != expected_report_sha256:
        raise ValueError(
            "legacy content exclusion report sha256 mismatch: "
            f"expected={expected_report_sha256} actual={actual_report_sha256}"
        )
    report = _load_json(report_path)
    report_index_schema = str(report.get("index_schema") or "")
    if (
        str(report.get("schema")) != LEGACY_EXCLUSION_SCHEMA
        or str(report.get("status")) != "complete"
        or report_index_schema
        not in {
            LEGACY_INDEX_SCHEMA,
            LEGACY_DEPRECATED_NEAR_INDEX_SCHEMA,
            LEGACY_NEAR_INDEX_SCHEMA,
        }
    ):
        raise ValueError("legacy content exclusion report is incomplete or unsupported")
    if (
        match_mode == "exact_sha256_plus_cdc_minhash8_near_overlap"
        and report_index_schema != LEGACY_NEAR_INDEX_SCHEMA
    ):
        raise ValueError("legacy near-content exclusion requires the v2 index schema")
    near_threshold = float(config.get("near_similarity_threshold", 0.75))
    if match_mode == "exact_sha256_plus_cdc_minhash8_near_overlap":
        near_config = report.get("near_duplicate_index")
        expected_near_config = {
            "signature_size": 8,
            "bands": 4,
            "band_size": 2,
            "minimum_similarity": 0.75,
        }
        if not isinstance(near_config, dict) or any(
            float(near_config.get(key, -1)) != float(value)
            for key, value in expected_near_config.items()
        ):
            raise ValueError("legacy near-content index parameters are unsupported")
        if near_threshold != 0.75:
            raise ValueError(
                "legacy near-content similarity threshold must remain 0.75"
            )
        if int(report.get("unique_signatures") or 0) <= 0:
            raise ValueError("legacy near-content exclusion report has no signatures")
    expected_manifest_sha256 = str(
        config.get("candidate_manifest_sha256") or ""
    ).lower()
    if expected_manifest_sha256:
        if (
            len(expected_manifest_sha256) != 64
            or str(report.get("candidate_manifest_sha256") or "").lower()
            != expected_manifest_sha256
        ):
            raise ValueError("legacy exclusion candidate manifest mismatch")
    else:
        repo_root = Path(__file__).resolve().parents[4]
        expected_roots = {
            (
                Path(str(value)).expanduser()
                if Path(str(value)).expanduser().is_absolute()
                else repo_root / Path(str(value)).expanduser()
            ).resolve()
            for value in config.get("required_corpus_roots", [])
        }
        actual_roots = {
            Path(value).resolve() for value in report.get("corpus_roots", [])
        }
        if not expected_roots or not _same_filesystem_objects(
            expected_roots, actual_roots
        ):
            raise ValueError(
                "legacy exclusion corpus roots mismatch: "
                f"expected={sorted(map(str, expected_roots))} "
                f"actual={sorted(map(str, actual_roots))}"
            )
    if (
        int(report.get("candidate_files") or 0) <= 0
        or int(report.get("processed_files") or 0)
        != int(report.get("candidate_files") or 0)
        or int(report.get("unique_hashes") or 0) <= 0
    ):
        raise ValueError("legacy content exclusion report has incomplete coverage")
    database_sha256 = str(report.get("database_sha256") or "")
    if database_sha256 != expected_database_sha256:
        raise ValueError(
            "legacy content exclusion database pin mismatch: "
            f"policy={expected_database_sha256} report={database_sha256}"
        )
    database_path = _select_verified_legacy_database_path(
        report=report,
        expected_sha256=database_sha256,
    )
    return LegacyContentExclusion(
        report_path=report_path,
        database_path=database_path,
        report_sha256=actual_report_sha256,
        database_sha256=database_sha256,
        index_schema=report_index_schema,
        near_threshold=near_threshold,
        action=action,
    )


def _select_verified_legacy_database_path(
    *,
    report: dict[str, Any],
    expected_sha256: str,
) -> Path:
    candidates: list[Path] = []
    override = str(
        os.environ.get("SOPHIA_LEGACY_EXCLUSION_DATABASE_PATH") or ""
    ).strip()
    if override:
        candidates.append(Path(override).expanduser().resolve())
    for key in ("working_database_path", "database_path"):
        value = str(report.get(key) or "").strip()
        if not value:
            continue
        path = Path(value).expanduser().resolve()
        if path not in candidates:
            candidates.append(path)
    if not candidates:
        raise FileNotFoundError("legacy content exclusion report has no database path")
    mismatches: list[str] = []
    for path in candidates:
        if not path.is_file():
            mismatches.append(f"{path}:missing")
            continue
        actual_sha256 = sha256_file(path)
        if actual_sha256 == str(expected_sha256):
            return path
        mismatches.append(f"{path}:{actual_sha256}")
    raise ValueError(
        "legacy content exclusion database sha256 mismatch: "
        f"recorded={expected_sha256} candidates={mismatches}"
    )


class ChineseQualityProxy:
    def __init__(
        self,
        *,
        artifact: dict[str, Any] | None = None,
        report_path: Path | None = None,
        report_sha256: str = "",
        model_sha256: str = "",
        labels_sha256: str = "",
        minimum_score: float = 0.0,
        minimum_cjk_ratio: float = 1.0,
        applicable_source_names: tuple[str, ...] = (),
        curated_source_exemptions: tuple[dict[str, str], ...] = (),
    ) -> None:
        self.artifact = artifact
        self.report_path = report_path
        self.report_sha256 = str(report_sha256)
        self.model_sha256 = str(model_sha256)
        self.labels_sha256 = str(labels_sha256)
        self.minimum_score = float(minimum_score)
        self.minimum_cjk_ratio = float(minimum_cjk_ratio)
        self.applicable_source_names = tuple(
            str(value).casefold() for value in applicable_source_names
        )
        self.curated_source_exemptions = tuple(curated_source_exemptions)

    @property
    def enabled(self) -> bool:
        return self.artifact is not None

    def is_exempt(self, *, repo_id: str, revision: str) -> bool:
        key = (str(repo_id).casefold(), str(revision).casefold())
        return any(
            key
            == (
                str(row["repo_id"]).casefold(),
                str(row["revision"]).casefold(),
            )
            for row in self.curated_source_exemptions
        )

    def applies(
        self,
        *,
        cjk_ratio: float,
        language: str,
        source_name: str = "",
        repo_id: str = "",
        revision: str = "",
    ) -> bool:
        return (
            self.enabled
            and str(language).casefold() != "code"
            and str(source_name).casefold() in self.applicable_source_names
            and float(cjk_ratio) >= self.minimum_cjk_ratio
            and not self.is_exempt(repo_id=repo_id, revision=revision)
        )

    def score(self, texts: list[str]) -> list[float]:
        if self.artifact is None:
            raise RuntimeError("Chinese quality proxy is not enabled")
        return [
            float(value) for value in score_quality_texts(self.artifact, list(texts))
        ]


def _load_curated_source_exemptions(
    *,
    config: dict[str, Any],
) -> tuple[dict[str, str], ...]:
    raw_rows = config.get("curated_source_exemptions", [])
    if not isinstance(raw_rows, list):
        raise ValueError("Chinese quality proxy curated exemptions must be a list")
    exemptions: list[dict[str, str]] = []
    seen: set[tuple[str, str]] = set()
    for raw in raw_rows:
        if not isinstance(raw, dict):
            raise ValueError("Chinese quality proxy curated exemptions must be objects")
        repo_id = str(raw.get("repo_id") or "").strip()
        revision = str(raw.get("revision") or "").strip().lower()
        reason = str(raw.get("reason") or "").strip()
        expected_sha256 = str(raw.get("evidence_report_sha256") or "").lower()
        evidence_value = str(raw.get("evidence_report_path") or "").strip()
        if (
            not repo_id
            or not revision
            or not reason
            or len(expected_sha256) != 64
            or not evidence_value
        ):
            raise ValueError("Chinese quality proxy curated exemption is incomplete")
        evidence_path = _resolve_policy_path(evidence_value)
        key = (repo_id.casefold(), revision)
        if key in seen:
            raise ValueError(f"duplicate Chinese quality proxy exemption: {repo_id}")
        seen.add(key)
        actual_sha256 = _json_sha256(evidence_path)
        if actual_sha256 != expected_sha256:
            raise ValueError(
                "Chinese quality proxy exemption evidence SHA-256 mismatch: "
                f"recorded={expected_sha256} actual={actual_sha256}"
            )
        evidence = _load_json(evidence_path)
        source = evidence.get("source")
        gates = evidence.get("gate_results")
        if (
            str(evidence.get("schema"))
            != "sophia_curated_chinese_source_proxy_exemption_v1"
            or str(evidence.get("status")) != "pass"
            or not isinstance(source, dict)
            or str(source.get("repo_id") or "").casefold() != repo_id.casefold()
            or str(source.get("revision") or "").lower() != revision
            or not isinstance(gates, dict)
            or not gates
            or not all(value is True for value in gates.values())
        ):
            raise ValueError(
                f"Chinese quality proxy exemption evidence did not pass: {repo_id}"
            )
        exemptions.append(
            {
                "repo_id": repo_id,
                "revision": revision,
                "reason": reason,
                "evidence_report_path": str(evidence_path),
                "evidence_report_sha256": expected_sha256,
            }
        )
    return tuple(exemptions)


def _load_chinese_quality_proxy(*, policy: dict[str, Any]) -> ChineseQualityProxy:
    config = policy.get("chinese_quality_proxy")
    if not isinstance(config, dict):
        return ChineseQualityProxy()
    if not bool(config.get("required")):
        raise ValueError("configured Chinese quality proxy must be required")
    report_path = _resolve_policy_path(config.get("report_path"))
    expected_report_sha256 = str(config.get("report_sha256") or "").lower()
    if len(expected_report_sha256) != 64:
        raise ValueError("Chinese quality proxy requires a pinned report sha256")
    actual_report_sha256 = _json_sha256(report_path)
    if actual_report_sha256 != expected_report_sha256:
        raise ValueError(
            "Chinese quality proxy report SHA-256 mismatch: "
            f"recorded={expected_report_sha256} actual={actual_report_sha256}"
        )
    report = _load_json(report_path)
    if (
        str(report.get("schema")) != QUALITY_PROXY_REPORT_SCHEMA
        or str(report.get("status")) != "pass"
    ):
        raise ValueError("Chinese quality proxy report is not a supported pass report")
    gate_results = report.get("gate_results")
    if (
        not isinstance(gate_results, dict)
        or not gate_results
        or not all(value is True for value in gate_results.values())
    ):
        raise ValueError("Chinese quality proxy report has failed or missing gates")
    model = report.get("model")
    source = report.get("source")
    if not isinstance(model, dict) or not isinstance(source, dict):
        raise ValueError("Chinese quality proxy report has incomplete lineage")
    if str(model.get("schema")) != QUALITY_PROXY_MODEL_SCHEMA:
        raise ValueError("unsupported Chinese quality proxy model schema")
    model_path = Path(str(model.get("path") or "")).expanduser()
    if not model_path.is_absolute():
        model_path = report_path.parent / model_path
    model_path = model_path.resolve()
    model_sha256 = str(model.get("sha256") or "")
    artifact = load_quality_proxy(model_path, expected_sha256=model_sha256)
    if str(artifact.get("labels_sha256") or "") != str(
        source.get("labels_sha256") or ""
    ) or str(artifact.get("sklearn_version") or "") != str(
        model.get("sklearn_version") or ""
    ):
        raise ValueError("Chinese quality proxy artifact lineage does not match report")
    labels_path = Path(str(source.get("labels_path") or "")).expanduser()
    if not labels_path.is_absolute():
        labels_path = report_path.parent / labels_path
    labels_path = labels_path.resolve()
    if not labels_path.is_file():
        raise FileNotFoundError(f"Chinese quality labels are missing: {labels_path}")
    labels_sha256 = str(source.get("labels_sha256") or "")
    actual_labels_sha256 = sha256_file(labels_path)
    if actual_labels_sha256 != labels_sha256:
        raise ValueError(
            "Chinese quality label SHA-256 mismatch: "
            f"recorded={labels_sha256} actual={actual_labels_sha256}"
        )
    report_threshold = float(model.get("threshold"))
    minimum_score = float(config.get("minimum_score", report_threshold))
    if not report_threshold <= minimum_score <= 1.0:
        raise ValueError(
            "Chinese quality proxy minimum_score may not be lower than the "
            f"validated threshold {report_threshold}"
        )
    minimum_cjk_ratio = float(config.get("minimum_cjk_ratio", 0.25))
    if not 0.0 <= minimum_cjk_ratio <= 1.0:
        raise ValueError("Chinese quality proxy minimum_cjk_ratio must be in [0, 1]")
    raw_source_names = config.get("applicable_source_names")
    if not isinstance(raw_source_names, list) or not raw_source_names:
        raise ValueError(
            "Chinese quality proxy requires explicit applicable_source_names"
        )
    applicable_source_names = tuple(
        str(value).strip() for value in raw_source_names if str(value).strip()
    )
    if len(applicable_source_names) != len(raw_source_names):
        raise ValueError("Chinese quality proxy applicable source name is empty")
    curated_source_exemptions = _load_curated_source_exemptions(config=config)
    return ChineseQualityProxy(
        artifact=artifact,
        report_path=report_path,
        report_sha256=actual_report_sha256,
        model_sha256=model_sha256,
        labels_sha256=labels_sha256,
        minimum_score=minimum_score,
        minimum_cjk_ratio=minimum_cjk_ratio,
        applicable_source_names=applicable_source_names,
        curated_source_exemptions=curated_source_exemptions,
    )


def _language_ratios(text: str) -> tuple[float, float]:
    cjk = len(_CJK_RE.findall(text))
    latin = len(_LATIN_RE.findall(text))
    denominator = max(cjk + latin, 1)
    return float(cjk) / denominator, float(latin) / denominator


def clean_source_document(
    text: str,
    *,
    language: str,
    min_chars: int,
    source_name: str = "",
    source_path: str = "",
    reject_ocr_enumeration: bool = False,
    minimum_language_ratio: float | None = None,
) -> CleanDecision:
    if str(language).lower() != "code":
        return clean_document(
            text,
            language=language,
            min_chars=int(min_chars),
            reject_ocr_enumeration=bool(reject_ocr_enumeration),
            minimum_language_ratio=minimum_language_ratio,
        )
    cleaned = normalize_text(text)
    cjk_ratio, latin_ratio = _language_ratios(cleaned)
    if len(cleaned) < int(min_chars):
        return CleanDecision("", "too_short", cjk_ratio, latin_ratio)
    if is_poison_repetitive_text(cleaned):
        return CleanDecision("", "poison_repetition", cjk_ratio, latin_ratio)
    normalized_path = str(source_path).replace("\\", "/")
    if _CODE_VENDOR_PATH_RE.search(normalized_path):
        return CleanDecision("", "code_vendor", cjk_ratio, latin_ratio)
    header = cleaned[:4096]
    if _CODE_GENERATED_RE.search(header):
        return CleanDecision("", "code_generated", cjk_ratio, latin_ratio)
    if _CODE_PROPRIETARY_RE.search(header):
        return CleanDecision("", "code_proprietary", cjk_ratio, latin_ratio)
    if any(pattern.search(cleaned) for pattern in _CODE_SECRET_RES):
        return CleanDecision("", "code_secret", cjk_ratio, latin_ratio)
    if _CODE_BASE64_BLOB_RE.search(cleaned):
        return CleanDecision("", "code_embedded_blob", cjk_ratio, latin_ratio)
    lines = cleaned.splitlines()
    if not lines or sum(character.isalnum() for character in cleaned) < 32:
        return CleanDecision("", "code_without_content", cjk_ratio, latin_ratio)
    longest_line = max((len(line) for line in lines), default=0)
    if longest_line > 50_000 or (
        longest_line > 5_000 and longest_line >= int(len(cleaned) * 0.90)
    ):
        return CleanDecision("", "minified_or_binary_line", cjk_ratio, latin_ratio)
    return CleanDecision(cleaned, "", cjk_ratio, latin_ratio)


def length_bucket(character_count: int) -> str:
    count = int(character_count)
    if count < 2_000:
        return "chars_lt_2k"
    if count < 8_000:
        return "chars_2k_8k"
    if count < 32_000:
        return "chars_8k_32k"
    return "chars_ge_32k"


def document_time_year(value: object) -> str:
    match = _TIMESTAMP_YEAR_RE.match(str(value or "").strip())
    return str(match.group(1)) if match is not None else "unknown"


def _normalize_license(value: object) -> str:
    if isinstance(value, (list, tuple, set)):
        return " OR ".join(
            sorted({str(item).strip() for item in value if str(item).strip()})
        )
    if isinstance(value, dict):
        return json.dumps(value, ensure_ascii=False, sort_keys=True)
    return str(value or "").strip()


def _license_identifiers(value: object) -> set[str]:
    if isinstance(value, (list, tuple, set)):
        raw_values = [str(item) for item in value]
    elif isinstance(value, str):
        raw_values = re.split(r"\s*(?:,|\bOR\b|\bAND\b)\s*", value)
    elif value is None:
        raw_values = []
    else:
        raw_values = [str(value)]
    return {
        identifier.strip().casefold() for identifier in raw_values if identifier.strip()
    }


def _record_value(record: dict[str, Any], key: str) -> object:
    if not key:
        return None
    value: object = record
    for part in str(key).split("."):
        if not isinstance(value, dict):
            return None
        value = value.get(part)
    return value


def _iter_records(path: Path, source: dict[str, Any]) -> Iterator[dict[str, Any]]:
    record_format = str(source.get("record_format") or "parquet")
    if record_format == "parquet":
        parquet = pq.ParquetFile(path)
        available = set(parquet.schema_arrow.names)
        requested = {
            str(source.get(key) or "").split(".", 1)[0]
            for key in (
                "text_column",
                "title_column",
                "id_column",
                "url_column",
                "license_column",
                "language_column",
                "timestamp_column",
                "metadata_column",
            )
            if str(source.get(key) or "")
        }
        requested.update({"score", "source"})
        required_configured = {
            str(source.get(key) or "").split(".", 1)[0]
            for key in (
                "text_column",
                "title_column",
                "id_column",
                "url_column",
                "license_column",
                "language_column",
                "timestamp_column",
                "metadata_column",
            )
            if str(source.get(key) or "")
        }
        missing_configured = required_configured - available
        if missing_configured:
            raise ValueError(
                f"missing configured parquet columns {sorted(missing_configured)}: {path}"
            )
        columns = sorted(requested & available)
        text_column = str(source.get("text_column") or "text").split(".", 1)[0]
        if text_column not in columns:
            raise ValueError(f"missing text column {text_column!r}: {path}")
        for batch in parquet.iter_batches(batch_size=2_048, columns=columns):
            yield from batch.to_pylist()
        return
    if record_format in {"jsonl", "jsonl_gzip"}:
        opener = gzip.open if record_format == "jsonl_gzip" else open
        with opener(path, mode="rt", encoding="utf-8") as handle:
            for line_number, line in enumerate(handle, start=1):
                if not line.strip():
                    continue
                payload = json.loads(line)
                if not isinstance(payload, dict):
                    raise ValueError(f"non-object JSON row: {path}:{line_number}")
                yield payload
        return
    raise ValueError(f"unsupported record_format={record_format!r}: {path}")


_WORKER_QUALITY_PROXY: ChineseQualityProxy | None = None
_WORKER_LEGACY_EXCLUSION: LegacyContentExclusion | None = None


def _initialize_preprocess_worker(
    quality_proxy: ChineseQualityProxy,
    legacy_config: dict[str, object],
) -> None:
    global _WORKER_LEGACY_EXCLUSION, _WORKER_QUALITY_PROXY
    _WORKER_QUALITY_PROXY = quality_proxy
    database_value = str(legacy_config.get("database_path") or "")
    _WORKER_LEGACY_EXCLUSION = LegacyContentExclusion(
        database_path=Path(database_value) if database_value else None,
        index_schema=str(legacy_config.get("index_schema") or ""),
        near_threshold=float(legacy_config.get("near_threshold") or 0.75),
        action=str(legacy_config.get("action") or "exclude"),
    )


def _score_quality_candidates(
    candidates: list[dict[str, Any]],
    *,
    source: dict[str, Any],
    quality_proxy: ChineseQualityProxy,
) -> None:
    language = str(source.get("language") or "unknown")
    source_name = str(source.get("name") or "")
    repo_id = str(source.get("repo_id") or "")
    revision = str(source.get("revision") or "")
    quality_rows = [
        candidate
        for candidate in candidates
        if quality_proxy.applies(
            cjk_ratio=float(candidate["decision"].cjk_ratio),
            language=language,
            source_name=source_name,
            repo_id=repo_id,
            revision=revision,
        )
    ]
    if not quality_rows:
        return
    scores = quality_proxy.score([str(candidate["text"]) for candidate in quality_rows])
    for candidate, score in zip(quality_rows, scores, strict=True):
        candidate["quality_proxy_score"] = float(score)


def _prepare_and_score_worker(
    task: tuple[tuple[dict[str, Any], ...], dict[str, Any]],
) -> tuple[list[dict[str, Any]], dict[str, int]]:
    if _WORKER_QUALITY_PROXY is None or _WORKER_LEGACY_EXCLUSION is None:
        raise RuntimeError("preprocess worker is not initialized")
    records, source = task
    stats: Counter[str] = Counter()
    candidates = _prepare_clean_candidates(
        records,
        source=source,
        stats=stats,
    )
    candidates = _apply_legacy_overlap(
        candidates,
        legacy_exclusion=_WORKER_LEGACY_EXCLUSION,
        stats=stats,
    )
    _score_quality_candidates(
        candidates,
        source=source,
        quality_proxy=_WORKER_QUALITY_PROXY,
    )
    return candidates, dict(stats)


def _bounded_ordered_process_map(
    executor: ProcessPoolExecutor,
    tasks: Iterable[tuple[tuple[dict[str, Any], ...], dict[str, Any]]],
    *,
    max_pending: int,
) -> Iterator[tuple[list[dict[str, Any]], dict[str, int]]]:
    if int(max_pending) <= 0:
        raise ValueError("max_pending must be positive")
    task_iterator = iter(tasks)
    pending: deque[Future[tuple[list[dict[str, Any]], dict[str, int]]]] = deque()
    for _ in range(int(max_pending)):
        try:
            task = next(task_iterator)
        except StopIteration:
            break
        pending.append(executor.submit(_prepare_and_score_worker, task))
    while pending:
        yield pending.popleft().result()
        try:
            task = next(task_iterator)
        except StopIteration:
            continue
        pending.append(executor.submit(_prepare_and_score_worker, task))


def _prepare_clean_candidates(
    records: tuple[dict[str, Any], ...],
    *,
    source: dict[str, Any],
    stats: Counter[str],
) -> list[dict[str, Any]]:
    language = str(source.get("language") or "unknown")
    text_column = str(source.get("text_column") or "text")
    title_column = str(source.get("title_column") or "")
    id_column = str(source.get("id_column") or "")
    url_column = str(source.get("url_column") or "")
    license_column = str(source.get("license_column") or "")
    language_column = str(source.get("language_column") or "")
    timestamp_column = str(source.get("timestamp_column") or "")
    metadata_column = str(source.get("metadata_column") or "metadata")
    metadata_license_key = str(source.get("metadata_license_key") or "")
    metadata_timestamp_key = str(source.get("metadata_timestamp_key") or "")
    allowed_languages = {
        str(value).casefold() for value in source.get("allowed_languages", [])
    }
    allowed_licenses = {
        str(value).strip().casefold()
        for value in source.get("allowed_licenses", [])
        if str(value).strip()
    }
    min_chars = int(source.get("min_chars") or 200)
    source_name = str(source.get("name") or "")
    reject_ocr_enumeration = bool(source.get("reject_ocr_enumeration", False))
    minimum_language_ratio_value = source.get("minimum_language_ratio")
    minimum_language_ratio = (
        float(minimum_language_ratio_value)
        if minimum_language_ratio_value is not None
        else None
    )
    pending: list[dict[str, Any]] = []
    for record in records:
        stats["docs_in"] += 1
        if language_column and allowed_languages:
            upstream_language = str(
                _record_value(record, language_column) or ""
            ).casefold()
            if upstream_language not in allowed_languages:
                stats["drop_upstream_language"] += 1
                continue
        decision = clean_source_document(
            str(_record_value(record, text_column) or ""),
            language=language,
            min_chars=min_chars,
            source_name=source_name,
            source_path=str(
                _record_value(record, "path")
                or _record_value(record, "max_stars_repo_path")
                or ""
            ),
            reject_ocr_enumeration=reject_ocr_enumeration,
            minimum_language_ratio=minimum_language_ratio,
        )
        if decision.reason:
            stats[f"drop_{decision.reason}"] += 1
            continue
        text = decision.text
        title = str(_record_value(record, title_column) or "").strip()
        if title and not text.startswith(title):
            text = f"{title}\n\n{text}"
        final_cjk_ratio, final_latin_ratio = _language_ratios(text)
        metadata = _record_value(record, metadata_column)
        metadata = metadata if isinstance(metadata, dict) else {}
        license_value = _record_value(record, license_column)
        if license_value is None and metadata_license_key:
            license_value = _record_value(metadata, metadata_license_key)
        license_identifiers = _license_identifiers(license_value)
        if allowed_licenses and (
            not license_identifiers or not license_identifiers <= allowed_licenses
        ):
            stats["drop_disallowed_license"] += 1
            continue
        license_name = _normalize_license(
            license_value if license_value is not None else source.get("license")
        )
        if bool(source.get("reject_empty_license")) and not license_name:
            stats["drop_missing_license"] += 1
            continue
        normalized = dedup_normalize(text)
        document_sha256 = hashlib.sha256(normalized.encode("utf-8")).hexdigest()
        signature = near_duplicate_signature(text, size=8)
        quality_score_column = str(source.get("quality_score_column") or "score")
        quality_value = _record_value(record, quality_score_column)
        quality = str(
            quality_value
            if quality_value is not None
            else source.get("quality_score") or ""
        )
        document_id = str(_record_value(record, id_column) or "")
        if not document_id:
            document_id = str(metadata.get("id") or document_sha256)
        url = str(_record_value(record, url_column) or metadata.get("url") or "")
        timestamp_value = _record_value(record, timestamp_column)
        if timestamp_value is None and metadata_timestamp_key:
            timestamp_value = _record_value(metadata, metadata_timestamp_key)
        document_timestamp = str(timestamp_value or "").strip()
        pending.append(
            {
                "decision": decision,
                "text": text,
                "final_cjk_ratio": final_cjk_ratio,
                "final_latin_ratio": final_latin_ratio,
                "license": license_name,
                "normalized": normalized,
                "document_sha256": document_sha256,
                "near_signature_values": signature,
                "legacy_exact_overlap": False,
                "legacy_near_overlap": False,
                "quality": quality,
                "document_id": document_id,
                "url": url,
                "document_timestamp": document_timestamp,
                "quality_proxy_score": None,
            }
        )
    return pending


def _apply_legacy_overlap(
    candidates: list[dict[str, Any]],
    *,
    legacy_exclusion: LegacyContentExclusion,
    stats: Counter[str],
) -> list[dict[str, Any]]:
    retained: list[dict[str, Any]] = []
    matches = legacy_exclusion.classify_batch(
        [
            (
                str(candidate["document_sha256"]),
                tuple(candidate["near_signature_values"]),
            )
            for candidate in candidates
        ]
    )
    for candidate, (legacy_exact_overlap, legacy_near_overlap) in zip(
        candidates,
        matches,
        strict=True,
    ):
        candidate["legacy_exact_overlap"] = legacy_exact_overlap
        if legacy_exact_overlap:
            stats["legacy_exact_overlap"] += 1
            if legacy_exclusion.action == "exclude":
                stats["drop_legacy_exact_overlap"] += 1
                continue
        candidate["legacy_near_overlap"] = legacy_near_overlap
        if legacy_near_overlap:
            stats["legacy_near_overlap"] += 1
            if legacy_exclusion.action == "exclude":
                stats["drop_legacy_near_overlap"] += 1
                continue
        retained.append(candidate)
    return retained


def _signature_blob(signature: tuple[int, ...]) -> bytes:
    return struct.pack(f">{len(signature)}Q", *signature) if signature else b""


def _signature_from_blob(payload: bytes) -> tuple[int, ...]:
    if not payload:
        return ()
    count = len(payload) // 8
    return tuple(struct.unpack(f">{count}Q", payload))


def _band_keys(signature: tuple[int, ...]) -> tuple[bytes, ...]:
    if len(signature) < 8:
        return ()
    return tuple(
        bytes([band]) + struct.pack(">2Q", *signature[band * 2 : band * 2 + 2])
        for band in range(4)
    )


def _near_lookup_band_keys(signature: tuple[int, ...]) -> tuple[bytes, ...]:
    return _band_keys(signature)


class SqliteDeduper:
    def __init__(self, path: Path, *, near_threshold: float = 0.75) -> None:
        self.path = path
        self.near_threshold = float(near_threshold)
        self.connection = sqlite3.connect(str(path), timeout=120.0)
        self.connection.execute("PRAGMA journal_mode=WAL")
        self.connection.execute("PRAGMA synchronous=FULL")
        self.connection.executescript(
            """
            CREATE TABLE IF NOT EXISTS metadata (
                key TEXT PRIMARY KEY,
                value TEXT NOT NULL
            );
            CREATE TABLE IF NOT EXISTS documents (
                id INTEGER PRIMARY KEY,
                sha256 TEXT NOT NULL UNIQUE,
                signature BLOB NOT NULL
            );
            CREATE TABLE IF NOT EXISTS bands (
                band_key BLOB NOT NULL,
                document_id INTEGER NOT NULL
            );
            CREATE INDEX IF NOT EXISTS bands_key_idx ON bands(band_key);
            CREATE TABLE IF NOT EXISTS processed_files (
                input_path TEXT PRIMARY KEY,
                source TEXT NOT NULL,
                file_key TEXT NOT NULL,
                stage_rel TEXT NOT NULL,
                stats_json TEXT NOT NULL,
                output_files_json TEXT NOT NULL
            );
            """
        )

    def set_lineage(self, values: dict[str, str]) -> None:
        for key, value in values.items():
            existing = self.connection.execute(
                "SELECT value FROM metadata WHERE key = ?", (str(key),)
            ).fetchone()
            if existing is not None and str(existing[0]) != str(value):
                raise ValueError(
                    f"cleaning resume lineage mismatch for {key}: "
                    f"stored={existing[0]} current={value}"
                )
            self.connection.execute(
                "INSERT OR IGNORE INTO metadata(key, value) VALUES (?, ?)",
                (str(key), str(value)),
            )
        self.connection.commit()

    def begin(self) -> None:
        self.connection.execute("BEGIN IMMEDIATE")

    def commit(self) -> None:
        self.connection.commit()

    def rollback(self) -> None:
        self.connection.rollback()

    def add_if_unique(self, *, sha256: str, signature: tuple[int, ...]) -> str:
        return self.add_batch_if_unique([(str(sha256), tuple(signature))])[0]

    def add_batch_if_unique(
        self,
        documents: list[tuple[str, tuple[int, ...]]],
    ) -> list[str]:
        if not documents:
            return []
        existing_hashes: set[str] = set()
        for offset in range(0, len(documents), 500):
            hashes = [sha256 for sha256, _signature in documents[offset : offset + 500]]
            placeholders = ",".join("?" for _ in hashes)
            existing_hashes.update(
                str(row[0])
                for row in self.connection.execute(
                    f"SELECT sha256 FROM documents WHERE sha256 IN ({placeholders})",
                    tuple(hashes),
                )
            )

        document_bands = [_band_keys(signature) for _sha256, signature in documents]
        lookup_bands = [
            _near_lookup_band_keys(signature) for _sha256, signature in documents
        ]
        all_bands = sorted({band for bands in lookup_bands for band in bands})
        existing_by_band: dict[bytes, set[bytes]] = defaultdict(set)
        for offset in range(0, len(all_bands), 500):
            bands = all_bands[offset : offset + 500]
            placeholders = ",".join("?" for _ in bands)
            rows = self.connection.execute(
                "SELECT b.band_key, d.signature FROM bands b "
                "JOIN documents d ON d.id = b.document_id "
                f"WHERE b.band_key IN ({placeholders})",
                tuple(sqlite3.Binary(value) for value in bands),
            )
            for band, signature_blob in rows:
                existing_by_band[bytes(band)].add(bytes(signature_blob))

        batch_hashes: set[str] = set()
        batch_by_band: dict[bytes, set[bytes]] = defaultdict(set)
        accepted: list[tuple[str, tuple[int, ...], tuple[bytes, ...]]] = []
        reasons: list[str] = []
        for (sha256, signature), bands, candidate_bands in zip(
            documents,
            document_bands,
            lookup_bands,
            strict=True,
        ):
            if sha256 in existing_hashes or sha256 in batch_hashes:
                reasons.append("exact_duplicate")
                continue
            candidate_blobs: set[bytes] = set()
            for band in candidate_bands:
                candidate_blobs.update(existing_by_band.get(band, ()))
                candidate_blobs.update(batch_by_band.get(band, ()))
            near_duplicate = False
            for candidate_blob in candidate_blobs:
                candidate = _signature_from_blob(candidate_blob)
                similarity = near_signature_similarity(signature, candidate)
                if similarity >= self.near_threshold:
                    near_duplicate = True
                    break
            if near_duplicate:
                reasons.append("near_duplicate")
                continue
            reasons.append("")
            batch_hashes.add(sha256)
            signature_blob = _signature_blob(signature)
            for band in bands:
                batch_by_band[band].add(signature_blob)
            accepted.append((sha256, signature, bands))

        if not accepted:
            return reasons
        row = self.connection.execute(
            "SELECT COALESCE(MAX(id), 0) FROM documents"
        ).fetchone()
        first_id = int(row[0]) + 1
        document_rows = [
            (first_id + index, sha256, sqlite3.Binary(_signature_blob(signature)))
            for index, (sha256, signature, _bands) in enumerate(accepted)
        ]
        self.connection.executemany(
            "INSERT INTO documents(id, sha256, signature) VALUES (?, ?, ?)",
            document_rows,
        )
        self.connection.executemany(
            "INSERT INTO bands(band_key, document_id) VALUES (?, ?)",
            (
                (sqlite3.Binary(band), first_id + index)
                for index, (_sha256, _signature, bands) in enumerate(accepted)
                for band in bands
            ),
        )
        return reasons

    def processed(self, input_path: str) -> dict[str, Any] | None:
        row = self.connection.execute(
            "SELECT source, file_key, stage_rel, stats_json, output_files_json "
            "FROM processed_files WHERE input_path = ?",
            (str(input_path),),
        ).fetchone()
        if row is None:
            return None
        return {
            "source": str(row[0]),
            "file_key": str(row[1]),
            "stage_rel": str(row[2]),
            "stats": json.loads(str(row[3])),
            "output_files": json.loads(str(row[4])),
        }

    def mark_processed(
        self,
        *,
        input_path: str,
        source: str,
        file_key: str,
        stage_rel: str,
        stats: dict[str, Any],
        output_files: list[str],
    ) -> None:
        self.connection.execute(
            "INSERT INTO processed_files("
            "input_path, source, file_key, stage_rel, stats_json, output_files_json"
            ") VALUES (?, ?, ?, ?, ?, ?)",
            (
                str(input_path),
                str(source),
                str(file_key),
                str(stage_rel),
                json.dumps(stats, ensure_ascii=False, sort_keys=True),
                json.dumps(output_files, ensure_ascii=False, sort_keys=True),
            ),
        )

    def all_processed(self) -> list[dict[str, Any]]:
        rows = self.connection.execute(
            "SELECT input_path, source, file_key, stage_rel, stats_json, "
            "output_files_json FROM processed_files ORDER BY input_path"
        )
        return [
            {
                "input_path": str(row[0]),
                "source": str(row[1]),
                "file_key": str(row[2]),
                "stage_rel": str(row[3]),
                "stats": json.loads(str(row[4])),
                "output_files": json.loads(str(row[5])),
            }
            for row in rows
        ]

    def close(self) -> None:
        self.connection.close()


_OUTPUT_SCHEMA = pa.schema(
    [
        ("text", pa.string()),
        ("source", pa.string()),
        ("source_revision", pa.string()),
        ("repo_id", pa.string()),
        ("license", pa.string()),
        ("domain", pa.string()),
        ("quality_score", pa.string()),
        ("chinese_quality_proxy_score", pa.float32()),
        ("language", pa.string()),
        ("document_id", pa.string()),
        ("url", pa.string()),
        ("document_timestamp", pa.string()),
        ("document_sha256", pa.string()),
        ("near_signature", pa.string()),
        ("legacy_exact_overlap", pa.bool_()),
        ("legacy_near_overlap", pa.bool_()),
        ("source_file_sha256", pa.string()),
        ("character_count", pa.int64()),
        ("utf8_bytes", pa.int64()),
        ("length_bucket", pa.string()),
        ("mix_bucket", pa.string()),
        ("cjk_ratio", pa.float32()),
        ("latin_ratio", pa.float32()),
    ]
)


class _StagedWriters:
    def __init__(
        self,
        *,
        output_root: Path,
        stage_root: Path,
        source: str,
        file_key: str,
        rows_per_file: int,
    ) -> None:
        self.output_root = output_root
        self.stage_root = stage_root
        self.source = source
        self.file_key = file_key
        self.rows_per_file = int(rows_per_file)
        self.buffers: dict[str, list[dict[str, object]]] = defaultdict(list)
        self.indexes: Counter[str] = Counter()
        self.output_files: list[str] = []

    def append(self, split: str, row: dict[str, object]) -> None:
        self.buffers[str(split)].append(row)
        if len(self.buffers[str(split)]) >= self.rows_per_file:
            self.flush(str(split))

    def flush(self, split: str) -> None:
        rows = self.buffers.get(str(split), [])
        if not rows:
            return
        index = int(self.indexes[str(split)])
        stage_dir = self.stage_root / str(split)
        stage_dir.mkdir(parents=True, exist_ok=True)
        filename = f"part-{index:05d}.parquet"
        pq.write_table(
            pa.Table.from_pylist(rows, schema=_OUTPUT_SCHEMA),
            stage_dir / filename,
            compression="zstd",
        )
        final = self.output_root / self.source / str(split) / self.file_key / filename
        self.output_files.append(str(final.resolve()))
        self.indexes[str(split)] += 1
        self.buffers[str(split)] = []

    def close(self) -> None:
        for split in tuple(self.buffers):
            self.flush(split)


def _publish_stage(
    *,
    output_root: Path,
    stage_rel: str,
    source: str,
    file_key: str,
    output_files: list[str],
) -> None:
    stage_root = output_root / stage_rel
    if stage_root.exists():
        for split_dir in sorted(path for path in stage_root.iterdir() if path.is_dir()):
            target = output_root / source / split_dir.name / file_key
            if target.exists():
                raise RuntimeError(
                    f"refusing to replace published clean output: {target}"
                )
            target.parent.mkdir(parents=True, exist_ok=True)
            split_dir.replace(target)
        if stage_root.exists():
            stage_root.rmdir()
    missing = [path for path in output_files if not Path(path).is_file()]
    if missing:
        raise RuntimeError(
            f"processed file is missing published outputs: {missing[:3]}"
        )
    for value in output_files:
        parquet = pq.ParquetFile(value)
        if not parquet.schema_arrow.equals(_OUTPUT_SCHEMA):
            raise RuntimeError(f"published clean output schema mismatch: {value}")
        if int(parquet.metadata.num_rows) <= 0:
            raise RuntimeError(f"published clean output is empty: {value}")


def _benchmark_matchers(paths: list[str]) -> list[tuple[str, BenchmarkMatcher]]:
    matchers: list[tuple[str, BenchmarkMatcher]] = []
    for value in paths:
        path = Path(value).expanduser().resolve()
        signatures: list[tuple[str, str]] = []
        with path.open(encoding="utf-8") as handle:
            for index, line in enumerate(handle):
                row = json.loads(line)
                if not isinstance(row, dict):
                    continue
                case_id = str(row.get("id") or f"row_{index}")
                prompt = str(
                    row.get("prompt")
                    or row.get("question")
                    or row.get("instruction")
                    or ""
                )
                normalized = dedup_normalize(prompt)
                if len(normalized) >= 24:
                    signatures.append((case_id, normalized))
        matchers.append((path.name, BenchmarkMatcher(tuple(signatures))))
    return matchers


def _remove_benchmark_contamination(
    candidates: list[dict[str, Any]],
    *,
    matchers: list[tuple[str, BenchmarkMatcher]],
    stats: Counter[str],
    contamination: Counter[str],
) -> list[dict[str, Any]]:
    retained: list[dict[str, Any]] = []
    for candidate in candidates:
        contaminated = ""
        for benchmark_name, matcher in matchers:
            case_id = matcher.match(str(candidate["normalized"]))
            if case_id:
                contaminated = f"{benchmark_name}:{case_id}"
                break
        if contaminated:
            stats["drop_benchmark_contamination"] += 1
            contamination[contaminated] += 1
            continue
        retained.append(candidate)
    return retained


def _build_report(
    *,
    output_root: Path,
    acquisition_path: Path,
    acquisition_sha256: str,
    inventory_sha256: str,
    policy_sha256: str,
    benchmark_paths: list[str],
    legacy_exclusion: LegacyContentExclusion,
    quality_proxy: ChineseQualityProxy,
    deduper: SqliteDeduper,
    include_output_hashes: bool = False,
) -> dict[str, Any]:
    sources: dict[str, dict[str, Any]] = {}
    for row in deduper.all_processed():
        source = str(row["source"])
        entry = sources.setdefault(
            source,
            {
                "name": source,
                "processed_input_files": 0,
                "stats": Counter(),
                "split_docs": Counter(),
                "split_utf8_bytes": Counter(),
                "length_buckets": Counter(),
                "document_time_years": Counter(),
                "licenses": Counter(),
                "benchmark_contamination": Counter(),
                "output_files": [],
            },
        )
        stats = row["stats"]
        entry["processed_input_files"] += 1
        entry["stats"].update(stats.get("stats", {}))
        entry["split_docs"].update(stats.get("split_docs", {}))
        entry["split_utf8_bytes"].update(stats.get("split_utf8_bytes", {}))
        entry["length_buckets"].update(stats.get("length_buckets", {}))
        entry["document_time_years"].update(stats.get("document_time_years", {}))
        entry["licenses"].update(stats.get("licenses", {}))
        entry["benchmark_contamination"].update(
            stats.get("benchmark_contamination", {})
        )
        entry["output_files"].extend(row["output_files"])
    normalized_sources: list[dict[str, Any]] = []
    for source in sources.values():
        normalized = {
            key: (dict(sorted(value.items())) if isinstance(value, Counter) else value)
            for key, value in source.items()
        }
        if include_output_hashes:
            inventory: list[dict[str, object]] = []
            output_rows = 0
            for path in normalized["output_files"]:
                parquet = pq.ParquetFile(path)
                if not parquet.schema_arrow.equals(_OUTPUT_SCHEMA):
                    raise RuntimeError(f"clean output schema mismatch: {path}")
                rows = int(parquet.metadata.num_rows)
                output_rows += rows
                inventory.append(
                    {
                        "path": str(Path(path).resolve()),
                        "bytes": int(Path(path).stat().st_size),
                        "rows": rows,
                        "sha256": sha256_file(path),
                    }
                )
            expected_rows = int(normalized["stats"].get("docs_kept", 0))
            if output_rows != expected_rows:
                raise RuntimeError(
                    f"clean output row count mismatch for {normalized['name']}: "
                    f"report={expected_rows} parquet={output_rows}"
                )
            normalized["validated_output_rows"] = output_rows
            normalized["output_file_inventory"] = inventory
        normalized_sources.append(normalized)
    return {
        "schema": REPORT_SCHEMA,
        "status": "in_progress",
        "acquisition_report": str(acquisition_path),
        "acquisition_report_sha256": acquisition_sha256,
        "inventory_sha256": inventory_sha256,
        "admission_policy_sha256": policy_sha256,
        "legacy_content_exclusion_report": (
            str(legacy_exclusion.report_path) if legacy_exclusion.report_path else ""
        ),
        "legacy_content_exclusion_report_sha256": legacy_exclusion.report_sha256,
        "legacy_content_exclusion_database": (
            str(legacy_exclusion.database_path)
            if legacy_exclusion.database_path
            else ""
        ),
        "legacy_content_exclusion_database_sha256": legacy_exclusion.database_sha256,
        "legacy_content_exclusion_index_schema": legacy_exclusion.index_schema,
        "legacy_content_overlap_action": legacy_exclusion.action,
        "chinese_quality_proxy_report": (
            str(quality_proxy.report_path) if quality_proxy.report_path else ""
        ),
        "chinese_quality_proxy_report_sha256": quality_proxy.report_sha256,
        "chinese_quality_proxy_model_sha256": quality_proxy.model_sha256,
        "chinese_quality_proxy_labels_sha256": quality_proxy.labels_sha256,
        "chinese_quality_proxy_minimum_score": (
            quality_proxy.minimum_score if quality_proxy.enabled else None
        ),
        "chinese_quality_proxy_minimum_cjk_ratio": (
            quality_proxy.minimum_cjk_ratio if quality_proxy.enabled else None
        ),
        "chinese_quality_proxy_applicable_source_names": list(
            getattr(quality_proxy, "applicable_source_names", ())
        ),
        "chinese_quality_proxy_curated_source_exemptions": list(
            quality_proxy.curated_source_exemptions
        ),
        "output_root": str(output_root),
        "state_database": str(deduper.path.resolve()),
        "split_policy": "sha256_mod_10000: train<9600, val<9800, else test",
        "exact_dedup": "sqlite unique sha256(NFKC+casefold+remove_whitespace)",
        "near_dedup": (
            "coordinate MinHash8 over content-defined chunks, four "
            "2-coordinate bands, coordinate agreement>=0.75"
        ),
        "benchmark_jsonl": [
            str(Path(path).expanduser().resolve()) for path in benchmark_paths
        ],
        "sources": sorted(normalized_sources, key=lambda value: str(value["name"])),
    }


def _write_progress_report_if_due(
    *,
    processed_now: int,
    report_every_input_files: int,
    output_root: Path,
    acquisition_path: Path,
    acquisition_sha256: str,
    inventory_sha256: str,
    policy_sha256: str,
    benchmark_paths: list[str],
    legacy_exclusion: LegacyContentExclusion,
    quality_proxy: ChineseQualityProxy,
    deduper: SqliteDeduper,
) -> None:
    if int(processed_now) % int(report_every_input_files) != 0:
        return
    report = _build_report(
        output_root=output_root,
        acquisition_path=acquisition_path,
        acquisition_sha256=acquisition_sha256,
        inventory_sha256=inventory_sha256,
        policy_sha256=policy_sha256,
        benchmark_paths=benchmark_paths,
        legacy_exclusion=legacy_exclusion,
        quality_proxy=quality_proxy,
        deduper=deduper,
    )
    write_json_atomic(output_root / "cleaning_report.json", report, sort_keys=True)


def clean_pretrain_corpus(
    *,
    acquisition_report: str,
    output_root: str,
    admission_policy: str,
    benchmark_jsonl: list[str] | None = None,
    rows_per_file: int = 10_000,
    max_input_files: int = 0,
    quality_score_batch_size: int = 512,
    working_state_database: str = "",
    preprocess_workers: int = 1,
    report_every_input_files: int = 1,
) -> dict[str, Any]:
    acquisition, inventory, policy, policy_sha256, inventory_sha256 = (
        _validate_acquisition(
            acquisition_path=acquisition_report,
            policy_path=admission_policy,
        )
    )
    del inventory
    legacy_exclusion = _load_legacy_content_exclusion(policy=policy)
    quality_proxy = _load_chinese_quality_proxy(policy=policy)
    if int(quality_score_batch_size) <= 0:
        raise ValueError("quality_score_batch_size must be positive")
    if int(preprocess_workers) <= 0:
        raise ValueError("preprocess_workers must be positive")
    if int(report_every_input_files) <= 0:
        raise ValueError("report_every_input_files must be positive")
    acquisition_path = Path(acquisition_report).expanduser().resolve()
    acquisition_sha256 = _json_sha256(acquisition_path)
    acquisition_content_sha256 = _acquisition_content_sha256(acquisition)
    root = Path(output_root).expanduser().resolve()
    state_path = (
        Path(working_state_database).expanduser().resolve()
        if str(working_state_database).strip()
        else root / "cleaning_state.sqlite3"
    )
    if root.exists() and any(root.iterdir()) and not state_path.is_file():
        raise ValueError(f"non-empty output_root is not a resumable clean run: {root}")
    root.mkdir(parents=True, exist_ok=True)
    state_path.parent.mkdir(parents=True, exist_ok=True)
    benchmarks = _validate_benchmark_decontamination(
        policy=policy,
        benchmark_paths=list(benchmark_jsonl or []),
    )
    benchmark_hashes = {
        str(Path(path).resolve()): sha256_file(path) for path in benchmarks
    }
    deduper = SqliteDeduper(state_path)
    deduper.set_lineage(
        {
            "acquisition_content_sha256": acquisition_content_sha256,
            "inventory_sha256": inventory_sha256,
            "policy_sha256": policy_sha256,
            "legacy_exclusion_report_sha256": legacy_exclusion.report_sha256,
            "legacy_exclusion_database_sha256": legacy_exclusion.database_sha256,
            "legacy_content_overlap_action": legacy_exclusion.action,
            "quality_proxy_report_sha256": quality_proxy.report_sha256,
            "quality_proxy_model_sha256": quality_proxy.model_sha256,
            "quality_proxy_labels_sha256": quality_proxy.labels_sha256,
            "quality_proxy_minimum_score": str(quality_proxy.minimum_score),
            "quality_proxy_minimum_cjk_ratio": str(quality_proxy.minimum_cjk_ratio),
            "quality_proxy_applicable_source_names": json.dumps(
                getattr(quality_proxy, "applicable_source_names", ()),
                ensure_ascii=False,
                sort_keys=True,
            ),
            "quality_proxy_curated_source_exemptions": json.dumps(
                quality_proxy.curated_source_exemptions,
                ensure_ascii=False,
                sort_keys=True,
            ),
            "benchmark_decontamination_assets": json.dumps(
                benchmark_hashes,
                ensure_ascii=False,
                sort_keys=True,
            ),
            "output_root": str(root),
        }
    )
    matchers = _benchmark_matchers(benchmarks)
    processed_now = 0
    executor: ProcessPoolExecutor | None = None
    try:
        if int(preprocess_workers) > 1:
            executor = ProcessPoolExecutor(
                max_workers=int(preprocess_workers),
                mp_context=multiprocessing.get_context("spawn"),
                initializer=_initialize_preprocess_worker,
                initargs=(
                    quality_proxy,
                    {
                        "database_path": str(legacy_exclusion.database_path or ""),
                        "index_schema": legacy_exclusion.index_schema,
                        "near_threshold": legacy_exclusion.near_threshold,
                        "action": legacy_exclusion.action,
                    },
                ),
            )
        for source in _ordered_acquisition_sources(acquisition):
            source_name = str(source.get("name") or "")
            language = str(source.get("language") or "unknown")
            source_repo_id = str(source.get("repo_id") or "")
            source_revision = str(source.get("revision") or "")
            quality_proxy_exempt = quality_proxy.is_exempt(
                repo_id=source_repo_id,
                revision=source_revision,
            )
            for file_index, file_info in enumerate(source.get("files", [])):
                if int(max_input_files) > 0 and processed_now >= int(max_input_files):
                    report = _build_report(
                        output_root=root,
                        acquisition_path=acquisition_path,
                        acquisition_sha256=acquisition_sha256,
                        inventory_sha256=inventory_sha256,
                        policy_sha256=policy_sha256,
                        benchmark_paths=benchmarks,
                        legacy_exclusion=legacy_exclusion,
                        quality_proxy=quality_proxy,
                        deduper=deduper,
                    )
                    write_json_atomic(
                        root / "cleaning_report.json", report, sort_keys=True
                    )
                    return report
                input_path = Path(str(file_info.get("path") or "")).resolve()
                input_key = str(input_path)
                file_key = (
                    f"input-{file_index:05d}-{str(file_info.get('sha256') or '')[:8]}"
                )
                stage_rel = str(Path(".staging") / source_name / file_key)
                existing = deduper.processed(input_key)
                if existing is not None:
                    _publish_stage(
                        output_root=root,
                        stage_rel=str(existing["stage_rel"]),
                        source=source_name,
                        file_key=str(existing["file_key"]),
                        output_files=list(existing["output_files"]),
                    )
                    continue
                if not input_path.is_file():
                    raise FileNotFoundError(
                        f"missing acquired source file: {input_path}"
                    )
                if int(input_path.stat().st_size) != int(file_info.get("bytes") or 0):
                    raise RuntimeError(f"source file size changed: {input_path}")
                if sha256_file(input_path) != str(file_info.get("sha256") or ""):
                    raise RuntimeError(f"source file hash changed: {input_path}")
                stage_root = root / stage_rel
                if stage_root.exists():
                    shutil.rmtree(stage_root)
                writers = _StagedWriters(
                    output_root=root,
                    stage_root=stage_root,
                    source=source_name,
                    file_key=file_key,
                    rows_per_file=int(rows_per_file),
                )
                stats: Counter[str] = Counter()
                split_docs: Counter[str] = Counter()
                split_bytes: Counter[str] = Counter()
                length_buckets: Counter[str] = Counter()
                document_time_years: Counter[str] = Counter()
                licenses: Counter[str] = Counter()
                contamination: Counter[str] = Counter()
                deduper.begin()
                try:
                    record_batches = batched(
                        _iter_records(input_path, source),
                        int(quality_score_batch_size),
                    )
                    if executor is None:
                        prepared_batches = (
                            (
                                _prepare_clean_candidates(
                                    records,
                                    source=source,
                                    stats=stats,
                                ),
                                None,
                            )
                            for records in record_batches
                        )
                    else:
                        prepared_batches = _bounded_ordered_process_map(
                            executor,
                            ((records, source) for records in record_batches),
                            max_pending=2 * int(preprocess_workers),
                        )
                    for pending, worker_stats in prepared_batches:
                        if worker_stats is not None:
                            stats.update(worker_stats)
                        if executor is None:
                            pending = _apply_legacy_overlap(
                                pending,
                                legacy_exclusion=legacy_exclusion,
                                stats=stats,
                            )
                            _score_quality_candidates(
                                pending,
                                source=source,
                                quality_proxy=quality_proxy,
                            )

                        quality_retained: list[dict[str, Any]] = []
                        for candidate in pending:
                            proxy_score = candidate["quality_proxy_score"]
                            if (
                                quality_proxy_exempt
                                and language.casefold() != "code"
                                and float(candidate["decision"].cjk_ratio)
                                >= quality_proxy.minimum_cjk_ratio
                            ):
                                stats["chinese_quality_proxy_curated_exempt_docs"] += 1
                            if proxy_score is not None:
                                stats["chinese_quality_proxy_docs_scored"] += 1
                                score_bucket = min(int(float(proxy_score) * 10), 9)
                                stats[
                                    f"chinese_quality_proxy_score_0_{score_bucket}x"
                                ] += 1
                                if float(proxy_score) < quality_proxy.minimum_score:
                                    stats["drop_chinese_quality_proxy"] += 1
                                    continue
                            quality_retained.append(candidate)
                        decontaminated = _remove_benchmark_contamination(
                            quality_retained,
                            matchers=matchers,
                            stats=stats,
                            contamination=contamination,
                        )
                        duplicate_reasons = deduper.add_batch_if_unique(
                            [
                                (
                                    str(candidate["document_sha256"]),
                                    tuple(candidate["near_signature_values"]),
                                )
                                for candidate in decontaminated
                            ]
                        )
                        for candidate, duplicate_reason in zip(
                            decontaminated,
                            duplicate_reasons,
                            strict=True,
                        ):
                            proxy_score = candidate["quality_proxy_score"]
                            text = str(candidate["text"])
                            document_sha256 = str(candidate["document_sha256"])
                            license_name = str(candidate["license"])
                            signature = tuple(candidate["near_signature_values"])
                            if duplicate_reason:
                                stats[f"drop_{duplicate_reason}"] += 1
                                continue
                            split = document_split(document_sha256)
                            utf8_bytes = len(text.encode("utf-8"))
                            bucket = length_bucket(len(text))
                            timestamp = str(candidate["document_timestamp"])
                            time_year = document_time_year(timestamp)
                            writers.append(
                                split,
                                {
                                    "text": text,
                                    "source": source_name,
                                    "source_revision": str(
                                        source.get("revision") or ""
                                    ),
                                    "repo_id": str(source.get("repo_id") or ""),
                                    "license": license_name,
                                    "domain": str(source.get("domain") or ""),
                                    "quality_score": str(candidate["quality"]),
                                    "chinese_quality_proxy_score": proxy_score,
                                    "language": language,
                                    "document_id": str(candidate["document_id"]),
                                    "url": str(candidate["url"]),
                                    "document_timestamp": timestamp,
                                    "document_sha256": document_sha256,
                                    "near_signature": ",".join(
                                        f"{value:016x}" for value in signature
                                    ),
                                    "legacy_exact_overlap": bool(
                                        candidate["legacy_exact_overlap"]
                                    ),
                                    "legacy_near_overlap": bool(
                                        candidate["legacy_near_overlap"]
                                    ),
                                    "source_file_sha256": str(
                                        file_info.get("sha256") or ""
                                    ),
                                    "character_count": len(text),
                                    "utf8_bytes": utf8_bytes,
                                    "length_bucket": bucket,
                                    "mix_bucket": f"{source_name}|{bucket}",
                                    "cjk_ratio": float(candidate["final_cjk_ratio"]),
                                    "latin_ratio": float(
                                        candidate["final_latin_ratio"]
                                    ),
                                },
                            )
                            stats["docs_kept"] += 1
                            split_docs[split] += 1
                            split_bytes[split] += utf8_bytes
                            length_buckets[bucket] += 1
                            document_time_years[time_year] += 1
                            licenses[license_name] += 1
                    writers.close()
                    file_stats = {
                        "stats": dict(stats),
                        "split_docs": dict(split_docs),
                        "split_utf8_bytes": dict(split_bytes),
                        "length_buckets": dict(length_buckets),
                        "document_time_years": dict(document_time_years),
                        "licenses": dict(licenses),
                        "benchmark_contamination": dict(contamination),
                    }
                    deduper.mark_processed(
                        input_path=input_key,
                        source=source_name,
                        file_key=file_key,
                        stage_rel=stage_rel,
                        stats=file_stats,
                        output_files=writers.output_files,
                    )
                    deduper.commit()
                except BaseException:
                    deduper.rollback()
                    committed = deduper.processed(input_key) is not None
                    if stage_root.exists() and not committed:
                        shutil.rmtree(stage_root)
                    raise
                _publish_stage(
                    output_root=root,
                    stage_rel=stage_rel,
                    source=source_name,
                    file_key=file_key,
                    output_files=writers.output_files,
                )
                processed_now += 1
                _write_progress_report_if_due(
                    processed_now=processed_now,
                    report_every_input_files=report_every_input_files,
                    output_root=root,
                    acquisition_path=acquisition_path,
                    acquisition_sha256=acquisition_sha256,
                    inventory_sha256=inventory_sha256,
                    policy_sha256=policy_sha256,
                    benchmark_paths=benchmarks,
                    legacy_exclusion=legacy_exclusion,
                    quality_proxy=quality_proxy,
                    deduper=deduper,
                )
                print(
                    f"[CLEAN] source={source_name} file={file_index + 1}/"
                    f"{len(source.get('files', []))} in={stats['docs_in']:,} "
                    f"kept={stats['docs_kept']:,}",
                    flush=True,
                )
        report = _build_report(
            output_root=root,
            acquisition_path=acquisition_path,
            acquisition_sha256=acquisition_sha256,
            inventory_sha256=inventory_sha256,
            policy_sha256=policy_sha256,
            benchmark_paths=benchmarks,
            legacy_exclusion=legacy_exclusion,
            quality_proxy=quality_proxy,
            deduper=deduper,
            include_output_hashes=True,
        )
        report["status"] = "complete"
        write_json_atomic(root / "cleaning_report.json", report, sort_keys=True)
        return report
    finally:
        if executor is not None:
            executor.shutdown(wait=True, cancel_futures=True)
        deduper.close()
        legacy_exclusion.close()


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description="Clean, license-filter, deduplicate, and split the new pretrain corpus."
    )
    parser.add_argument("--acquisition-report", required=True)
    parser.add_argument("--output-root", required=True)
    parser.add_argument(
        "--admission-policy",
        default="configs/data/pretrain_data_admission_policy.json",
    )
    parser.add_argument("--benchmark-jsonl", action="append", default=[])
    parser.add_argument("--rows-per-file", type=int, default=10_000)
    parser.add_argument("--max-input-files", type=int, default=0)
    parser.add_argument("--quality-score-batch-size", type=int, default=512)
    parser.add_argument("--preprocess-workers", type=int, default=1)
    parser.add_argument("--report-every-input-files", type=int, default=1)
    parser.add_argument(
        "--working-state-database",
        default="",
        help="Place the resumable deduplication SQLite database on a native filesystem.",
    )
    return parser


def main(argv: list[str] | None = None) -> int:
    args = build_parser().parse_args(argv)
    report = clean_pretrain_corpus(
        acquisition_report=str(args.acquisition_report),
        output_root=str(args.output_root),
        admission_policy=str(args.admission_policy),
        benchmark_jsonl=[str(value) for value in args.benchmark_jsonl],
        rows_per_file=int(args.rows_per_file),
        max_input_files=int(args.max_input_files),
        quality_score_batch_size=int(args.quality_score_batch_size),
        working_state_database=str(args.working_state_database),
        preprocess_workers=int(args.preprocess_workers),
        report_every_input_files=int(args.report_every_input_files),
    )
    print(
        f"[DONE] status={report['status']} output={report['output_root']}",
        flush=True,
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
